# Generated by Django 2.0.13 on 2019-09-04 15:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('id_part', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_ped', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comidas.Participantes')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('name_prod', models.CharField(max_length=70)),
                ('desc_prod', models.CharField(max_length=250)),
                ('cantidad', models.PositiveIntegerField()),
                ('expira_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comidas.Productos'),
        ),
        migrations.AddField(
            model_name='participantes',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comidas.Productos'),
        ),
    ]
