# Generated by Django 2.0.13 on 2019-09-09 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comidas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='cantidad',
            new_name='cantidadp',
        ),
        migrations.RemoveField(
            model_name='participantes',
            name='product',
        ),
    ]
