# Generated by Django 2.0.13 on 2019-09-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comidas', '0002_auto_20190909_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='first_name',
            new_name='participante',
        ),
    ]
